### ISSUE TITLE
Node List not showing

### ISSUE THREAD

**Issue by umairsali07** [nicolastinkl/UUVPN#1]
Node List not showing

  new ServerEntity.fromMap (package:sail/entity/server_entity.dart:63:21)
E/flutter ( 9622): #1      serverEntityFromList.<anonymous closure> (package:sail/entity/server_entity.dart:8:58)
E/flutter ( 9622): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
E/flutter ( 9622): #3      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
E/flutter ( 9622): #4      new List.from (dart:core-patch/array_patch.dart:37:17)
E/flutter ( 9622): #5      serverEntityFromList (package:sail/entity/server_entity.dart:8:5)
E/flutter ( 9622): #6      ServerService.server.<anonymous closure> (package:sail/service/server_service.dart:8:14)
E/flutter ( 9622): <asynchronous suspension>
E/flutter ( 9622): #7      ServerModel.getServerList (package:sail/models/server_model.dart:37:27)
E/flutter ( 9622): <asynchronous suspension>
E/flutter ( 9622): #8      HomePageState.didChangeDependencies (package:sail/pages/home/home_page.dart:153:7)
E/flutter ( 9622): <asynchronous suspension>

**Comment by nicolastinkl** [comment]
You have chage domain.
